### ISSUE TITLE
大于3M的文件无法下载

### ISSUE THREAD

**Issue by TonyK-T** [yutent/dtalk-app#4]
发送的单文件大于3M ,就无法下载

**Comment by yutent** [comment]
我这边目测是可以的, 也有可能是我的操作步骤不是和你的一样。

另外, 临时的解决方案, 是在手机上转存到 钉盘 里, 然后再下载。

-----------------

这是脑残的钉钉自己作的死啦。我这个app, 只是给他们的在线聊天地址套一层electron, 方便在后台保持运行而已。
