### ISSUE TITLE
弹出窗口太小而且无法拖动放大

### ISSUE THREAD

**Issue by faonecze** [yutent/dtalk-app#6]
大佬RT,3.8.8弹出窗口太小而且无法拖动放大,linuxmint19.3

**Comment by yutent** [comment]
本来就是不能放大的, 因为放大也没意义。网页版的钉钉永远只有 1000*600的有效尺寸。

**Comment by faonecze** [comment]
打开`管理`和`钉邮`后的那个窗口大小宽度再大点就好了,默认界面窗口确实固定大小...

**Comment by yutent** [comment]
> 打开`管理`和`钉邮`后的那个窗口大小宽度再大点就好了,默认界面窗口确实固定大小...

这个我后面看看吧, 我们大概可能都要换掉钉钉了, 太辣鸡,太流氓了。
或者你自己下载源码修改, 自己打个包也可以的。
